# Change these first
owner: s-complex # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Ou's Intro
    url: https://www.gxres.net
    headers:
      - "User-Agent: curl/8.2.1 (https://status.slirv.vip)"
  - name: Restent's Notebook
    url: https://blog.gxres.net
    headers:
      - "User-Agent: curl/8.2.1 (https://status.slirv.vip)"
  - name: SliverRiver's Library
    url: https://library.gxres.net
    headers:
      - "User-Agent: curl/8.2.1 (https://status.slirv.vip)"
  - name: Friends linklist
    url: https://prox.slirv.vip/raw/S-Complex/Friends/main/links.json
    headers:
      - "User-Agent: curl/8.2.1 (https://status.slirv.vip)"
    method: GET
  - name: Upptime
    url: https://status.slirv.vip
    headers:
      - "User-Agent: curl/8.2.1 (https://status.slirv.vip)"

workflowSchedule:
  graphs: "0 */4 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.slirv.vip
  # baseUrl: /upptime
  logoUrl: https://library.gxres.net/images/icons/favicon.webp
  name: Ou's Site Status
  navbar:
    - title: Index
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: HomePage
      href: https://www.gxres.net
  singleCommit: true

commitMessages:
  commitAuthorName: "slivermoe"
  commitAuthorEmail: "148861329+slivermoe@users.noreply.github.com"

i18n:
  footer: Generated by [Upptime](https://upptime.js.org) | [Site source](https://github.com/s-complex/upptime)

user-agent: "slivermoe (https://github.com/s-complex/upptime)"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
